# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- script: echo 'Hello, world!'
  displayName: 'Run a one-line script'

- script: mvn clean install
  displayName: 'Run a multi-line script'

- script: mvn test
  displayName: 'Test the application'

- script: mvn exec:java -Dexec.mainClass=com.example.App
  displayName: 'Running the jar file'